### ISSUE TITLE
Write contents 3rd texts

### ISSUE THREAD

**Issue by Lee-Null** [Lee-Null/green-04#7]
3.Directions
   3.1.How to make a card news
       3.1.0.Create project
       3.1.1.Create Card News
       3.1.2.Delete Card News
       3.1.3.Create a text
       3.1.4.Create a template
       3.1.5.Share Card News
   3.2.Delete project
   3.3.Developers, license

**Comment by skqltldnjf** [comment]
3.1.0 
main(image)
"push the pencil button to create a cardnews project"
 pencil(image) 
"Write the project name"
create cardnews(image)

3.1.1
"Click the project" 
making card(image)
 "Press the add button for the desired number of images.
Push the save button and back"
create cardnews (image)
cardnews 1st place(image)
 cardnews 2nd place(image)
 "When you enter a card news project, you are assigned a page of images that you can put in"
 "Push the image button"
edit photo(image)
"You can edit the image if you want."
 "Put one image on one page, press save button and back." 
saved image(image)
saved another image(image) 
"Repeat this operation for each page"

**Comment by skqltldnjf** [comment]
3.1.2
making card(image)
"Push the delete button."
main(image)
3.1.3
"You can create a text if you want. click the text button"
click text(image)
"Write the title and text"
saved text(image)

**Comment by skqltldnjf** [comment]
3.1.4
"You can create template if you want. click the template button"
click template(image)
"Unfortunately, this app is still a prototype, so there is only one template type."
"Push the 1 button"
3.1.5
"Push the share button"
click share(image)
"Click on the link for the site you want to share"
share example-google drive(image)

**Comment by skqltldnjf** [comment]
3.2
create cardnews(image)
"Check the project and click the X button"
delete complete(image)

3.3
main(image)
"Click the | button"
other menu(image)
"You can check developer and license."

**Comment by Lee-Null** [comment]
Please fix the enter problem.
